# Generated by Django 5.1.1 on 2024-09-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_project_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_admin',
        ),
    ]
