# Generated by Django 5.1.1 on 2024-09-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_remove_project_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
